// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicTheory.Data.Music
{

    // Chord
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Chord
    {
        public int ChordId { get; set; } // ChordId (Primary key)
        public string ChordName { get; set; } // ChordName

        // Reverse navigation

        /// <summary>
        /// Child ChordNotes where [ChordNote].[ChordId] point to this entity (FK_Chord_ChordNote)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ChordNote> ChordNotes { get; set; } // ChordNote.FK_Chord_ChordNote

        public Chord()
        {
            ChordNotes = new System.Collections.Generic.List<ChordNote>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
