// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicTheory.Data.Music
{

    // ChordNote
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ChordNoteConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ChordNote>
    {
        public ChordNoteConfiguration()
            : this("dbo")
        {
        }

        public ChordNoteConfiguration(string schema)
        {
            ToTable("ChordNote", schema);
            HasKey(x => x.ChordNoteId);

            Property(x => x.ChordNoteId).HasColumnName(@"ChordNoteId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ChordId).HasColumnName(@"ChordId").HasColumnType("int").IsRequired();
            Property(x => x.Interval).HasColumnName(@"Interval").HasColumnType("int").IsOptional();

            // Foreign keys
            HasRequired(a => a.Chord).WithMany(b => b.ChordNotes).HasForeignKey(c => c.ChordId).WillCascadeOnDelete(false); // FK_Chord_ChordNote
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
