// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicTheory.Data.Music
{

    // ChordNote
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ChordNote
    {
        public int ChordNoteId { get; set; } // ChordNoteId (Primary key)
        public int ChordId { get; set; } // ChordId
        public int? Interval { get; set; } // Interval

        // Foreign keys

        /// <summary>
        /// Parent Chord pointed by [ChordNote].([ChordId]) (FK_Chord_ChordNote)
        /// </summary>
        public virtual Chord Chord { get; set; } // FK_Chord_ChordNote

        public ChordNote()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
