// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicTheory.Data.Music
{


    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class MusicContext : System.Data.Entity.DbContext, IMusicContext
    {
        public System.Data.Entity.DbSet<Chord> Chords { get; set; } // Chord
        public System.Data.Entity.DbSet<ChordNote> ChordNotes { get; set; } // ChordNote
        public System.Data.Entity.DbSet<MusicKey> MusicKeys { get; set; } // MusicKey
        public System.Data.Entity.DbSet<Note> Notes { get; set; } // Note
        public System.Data.Entity.DbSet<Scale> Scales { get; set; } // Scale
        public System.Data.Entity.DbSet<ScaleNote> ScaleNotes { get; set; } // ScaleNote

        static MusicContext()
        {
            System.Data.Entity.Database.SetInitializer<MusicContext>(null);
        }

        public MusicContext()
            : base("Name=MusicTheoryConnection")
        {
            InitializePartial();
        }

        public MusicContext(string connectionString)
            : base(connectionString)
        {
            InitializePartial();
        }

        public MusicContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
            InitializePartial();
        }

        public MusicContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
            InitializePartial();
        }

        public MusicContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
            InitializePartial();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new ChordConfiguration());
            modelBuilder.Configurations.Add(new ChordNoteConfiguration());
            modelBuilder.Configurations.Add(new MusicKeyConfiguration());
            modelBuilder.Configurations.Add(new NoteConfiguration());
            modelBuilder.Configurations.Add(new ScaleConfiguration());
            modelBuilder.Configurations.Add(new ScaleNoteConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new ChordConfiguration(schema));
            modelBuilder.Configurations.Add(new ChordNoteConfiguration(schema));
            modelBuilder.Configurations.Add(new MusicKeyConfiguration(schema));
            modelBuilder.Configurations.Add(new NoteConfiguration(schema));
            modelBuilder.Configurations.Add(new ScaleConfiguration(schema));
            modelBuilder.Configurations.Add(new ScaleNoteConfiguration(schema));
            return modelBuilder;
        }

        partial void InitializePartial();
        partial void OnModelCreatingPartial(System.Data.Entity.DbModelBuilder modelBuilder);
    }
}
// </auto-generated>
