// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicTheory.Data.Music
{

    // Note
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class NoteConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Note>
    {
        public NoteConfiguration()
            : this("dbo")
        {
        }

        public NoteConfiguration(string schema)
        {
            ToTable("Note", schema);
            HasKey(x => x.NoteId);

            Property(x => x.NoteId).HasColumnName(@"NoteId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NoteName).HasColumnName(@"NoteName").HasColumnType("nvarchar(max)").IsOptional();
           
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
