// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicTheory.Data.Music
{

    // ScaleNote
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ScaleNote
    {
        public int ScaleNoteId { get; set; } // ScaleNoteId (Primary key)
        public int ScaleId { get; set; } // ScaleId
        public int? Interval { get; set; } // Interval

        // Foreign keys

        /// <summary>
        /// Parent Scale pointed by [ScaleNote].([ScaleId]) (FK_ScaleNote_Scale)
        /// </summary>
        public virtual Scale Scale { get; set; } // FK_ScaleNote_Scale

        public ScaleNote()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
