// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicTheory.Data.Music
{

    // Scale
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Scale
    {
        public int ScaleId { get; set; } // ScaleId (Primary key)
        public string ScaleName { get; set; } // ScaleName

        // Reverse navigation

        /// <summary>
        /// Child ScaleNotes where [ScaleNote].[ScaleId] point to this entity (FK_ScaleNote_Scale)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ScaleNote> ScaleNotes { get; set; } // ScaleNote.FK_ScaleNote_Scale

        public Scale()
        {
            ScaleNotes = new System.Collections.Generic.List<ScaleNote>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
